### ISSUE TITLE
Design progress api

### ISSUE THREAD

**Issue by dcsiebe** [itslanguage/itslanguage-docs#46]
Document the api to get the progress for users.
The idea is to request progress for categories within a category, data should be returned nested so a single query will suffice.

URL: `/groups/:groupid/categories/:category/progress`

Output depends on the users permissions, if permissions are granted to see multiple users, multiple users are returned else the progress of the current user is returned.

Example output:

`GET /groups/group_2/categories/week_1/progress`
```json
[
    {
        "category": "lo_1",
        "percentage": 70,
        "user": {
            "id": "user_1",
            "profile": {
                "firstName": "Martin",
                "lastName": "van",
                "lastName": "Nostrand"
            }
        },
        "challenges": [
            {
                "id": "chal_1",
                "audioUrl": "....",
                "recording": {
                    "id": "rec_2",
                    "audioUrl": "...."
                }
            },
            {
                "id": "chal_2",
                "audioUrl": "....",
                "recording": null
            }
        ]
        
    },
    {
        "category": "lo_2",
        "percentage": 50,
        "user": {
            "id": "user_2",
            "profile": {
                "firstName": "Art",
                "lastName": "Vandelay",
                "infix": null
            }
        },
        "challenges": [
            {
                "id": "chal_1",
                "audioUrl": "....",
                "recording": {
                    "id": "rec_1",
                    "audioUrl": "...."
                }
            },
            {
                "id": "chal_2",
                "audioUrl": "....",
                "recording": null
            }
        ]
        
    }
]
```

**Comment by joggienl** [comment]
Some additional context (not mentioned in the issue yet):

- Current user -> see your own progress as a student
- Able to see multiple users -> teacher wants to see progress
- Profile information is added because of the teacher wanting to see progress of all possible students (and wants to know which progress goes with which student)

**Comment by kvdb** [comment]
Not sure if you want to provide the full user profile in this call multiple times as well. Perhaps user_id is enough and saves you some additional queries in the backend? Or did you have a specific purpose for this data in mind that I did not know?

In the URL I see you can select only the top level category. Ok, let's go with that. So I suppose I get nested subcategories in the results. Perhaps you can also show that in your example result to make sure we know how that works. I guess that will be a lot of data. Not really a problem though, but then I think: do we need all challenge metadata here too? I'm afraid that's a lot of extra backend work while the chal_ids themselves probably suffice?

**Comment by joggienl** [comment]
> Not sure if you want to provide the full user profile in this call multiple times as well. Perhaps user_id is enough and saves you some additional queries in the backend? Or did you have a specific purpose for this data in mind that I did not know?

I think you don't want to query 30 times to get an overview of a complete group with students. So having a basic profile in the response is fine.

**Comment by kvdb** [comment]
I'm not sure if the progress call is the right place for querying a group of students.
What about an extra API call if you need that: /groups/:groupid/users

**Comment by joggienl** [comment]
> In the URL I see you can select only the top level category. Ok, let's go with that. So I suppose I get nested subcategories in the results. Perhaps you can also show that in your example result to make sure we know how that works. I guess that will be a lot of data. Not really a problem though, but then I think: do we need all challenge metadata here too? I'm afraid that's a lot of extra backend work while the chal_ids themselves probably suffice?

The extra metadata is to be able to directly play audio (if it's there)

> I'm not sure if the progress call is the right place for querying a group of students.
What about an extra API call if you need that: /groups/:groupid/users

Could be indeed. But on the other hand we do know that we need this information now. Might be premature optimisation of this call? @dcsiebe?

**Comment by kvdb** [comment]
I'm just trying to make that API call as snappy as possible. I can tell you're thinking about CMS functionality. I can imagine that when you press the play button there, it fetches recording metadata first, then prefetches/streams audio. Playing audio is delayed a bit, but it saves you a lot of queries on the backend. I try to shift the weight that we because I anticipate a screen full of play buttons in the CMS and most play buttons there are probably not pressed.

**Comment by joggienl** [comment]
>  I can tell you're thinking about CMS functionality

Yes, but the use case is not the CMS itself. We need some CMS features without a CMS at first...

> I can imagine that when you press the play button there, it fetches recording metadata first, then prefetches/streams audio.

I was assuming that I do have the audioUrl already but not necessary the audio itself yet (that can be loaded once the user clicks the play button. To only have the challenge ID and get the rest (the recording) once the user clicks play gives a snappy API, but I would not prefer this from UX point of view.

**Comment by kvdb** [comment]
To obtain the audioUrl, I think the backend has to do a query in order to assemble each URL (it just fetches the speechrecording record), that's why I think it's quite heavy. From a UX POV, you also want a snappy API. Perhaps we can start out in a lightweight fashion and add data if we see no better alternative?

**Comment by joggienl** [comment]
> From a UX POV, you also want a snappy API.

Jup. It will take time to get data, so the question is what is the "best" place to let the user wait for data?

> Perhaps we can start out in a lightweight fashion and add data if we see no better alternative?

Calling progress does not always return challenges. If there are challenges, you want to know if there are recordings. If there are recordings, you want to know which ones. I'm not sure at this point if it's really heavier to just return the recording-ids or the ids and the url as well.

Maybe, as a future increment, proving the key of the location in store is enough to let the SDK compose the download URL? This does presume the download URL is always the same though (which is the case). As a side note to this side note, this might help in the secured url's discussion.

**Comment by dcsiebe** [comment]
I was thinking about duplicating the data in the backend. Progress will contain a nested entity so only a single query will return all required data. I think it's the quickest way to serve the data to the client.
When the backend gets simpler, the client needs to do more which will result in several round-trips, which will be slower imo.

**Comment by kvdb** [comment]
Duplicating data is no problem, as long as we can consistently do so.
